@startuml
entity 顧客 {
    顧客ID(PK)
    名前ローマ字
    苗字ローマ字
    名前漢字
    苗字漢字
    電話番号
}

entity 注文 {
    注文ID(PK)
    顧客ID(FK)
    注文日時
    支払い済み
    引き渡し済み
}

entity 商品 {
    商品ID(PK)
    商品名(Unique)
    単価
}

entity 注文詳細{
    注文ID(FK)
    商品ID(FK)
    個数
    さび抜き
}
顧客 ||---{ 注文
商品 }--|| 注文詳細
注文 ||---{ 注文詳細

@enduml