@startuml
entity 顧客 {
    顧客ID(PK)
    名前ローマ字
    苗字ローマ字
    名前漢字
    苗字漢字
    電話番号
}

entity 来店データ {
    来店ID(PK)
    顧客ID(FK)
    店舗ID(FK)
    来店時間
    満足度
}

entity 店舗 {
    店舗ID(PK)
    住所
    店長ID(FK)
}

entity 従業員 {
    従業員ID(PK)
    名前
    性別
    生年月日
    店舗ID(FK)
}

entity ネタ {
    ネタID(PK)
    ネタ名
}

entity 商品詳細 {
    商品詳細ID(PK)
    商品ID(FK)
    ネタID(FK)
    ネタ個数
    有効期間
}

entity 商品_追加オプション {
    商品ID_追加オプションID(PK)
    商品ID(FK)
    追加オプションID(FK)
}

entity 追加オプション {
    オプションID(PK)
    オプション名前
    単価
}

entity 単価 {
    単価ID(PK)
    商品ID(FK)
    単価
    有効期間
}

entity 注文 {
    注文ID(PK)
    顧客ID(FK)
    注文日時
    支払い済み
    引き渡し済み
}

entity 商品 {
    商品ID(PK)
    商品名(Unique)
    単価
    注文可
}

entity 注文詳細{
    注文ID(FK)
    商品ID(FK)
    個数
    さび抜き
    シャリ量
}
顧客 ||--{ 注文
顧客 ||--|| 来店データ
来店データ }--|| 店舗
店舗 ||--{ 従業員
注文 ||--{ 注文詳細


商品 }--|| 注文詳細
商品 ||--{ 商品詳細
商品詳細 ||--{ ネタ
商品 ||--{ 単価
商品 ||--{ 商品_追加オプション
商品_追加オプション }-- 追加オプション
@enduml